# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddbcb846d7b4d92fccb6b4284dc9aff973c62b743837a5fc455a76bfcb0f941148d34f0ede33f288847d8ae1032bfb63f9306f916c871f1cffcbb0e02a2c94e

test:
  secret_key_base: 8e3a139fe234c407f33dde567c4c7dc4c9aa06e0767a9d19e8484c3b95672353fa3dc31eef1bc883a1bb89a10373fa6e006f31d1af52d77426c43eba54942058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
